#ifndef BELT_P2PSOCKET_GLOBAL_H
#define BELT_P2PSOCKET_GLOBAL_H

#include <global.hpp>

#if defined(P2PSOCKET_LIBRARY)
#define P2PSOCKETSHARED_EXPORT BELT_EXPORT
#else
#define P2PSOCKETSHARED_EXPORT BELT_IMPORT
#endif

#endif// BELT_P2PSOCKET_GLOBAL_H
