#ifndef BELT_MESSAGECODES_GLOBAL_H
#define BELT_MESSAGECODES_GLOBAL_H

#include <global.hpp>

#if defined(MESSAGECODES_LIBRARY)
#define MESSAGECODESSHARED_EXPORT BELT_EXPORT
#else
#define MESSAGECODESSHARED_EXPORT BELT_IMPORT
#endif

#endif// BELT_MESSAGECODES_GLOBAL_H
